### ISSUE TITLE
How to launch training on 1070

### ISSUE THREAD

**Issue by darkcake** [Lotayou/Face-Renovation#13]
Hi. Can you tell how i can launch training process on GeForce 1070 (8 Gb)? 
Then I changed  nfg to 48 in config file ` ngf = 48 # set to 48 for Titan X 12GB card`
its displays this message `RuntimeError: CUDA out of memory. Tried to allocate 192.00 MiB (GPU 0; 8.00 GiB total capacity; 6.05 GiB already allocated; 95.55 MiB free; 108.68 MiB cached)`
That I can do to reduce model size and start taraining?

**Comment by Lotayou** [comment]
The easiest fix is to further reduce ngf to 32, but the performance could drop. Another way is to use a baseline version by changing `netG = 'spade'`, which disables the nested connection and adaptive convolution, and use the same output of `C*16*16` feature maps for all SPADE modules. This could reduce the memory cost down to 8 GB. If that still too heavy for you, try reduce the discriminator size and number of base filters (controlled by `n_layers` and `ndf`)
