### ISSUE TITLE
niqe

### ISSUE THREAD

**Issue by dan520520520** [Lotayou/Face-Renovation#14]
你好，可以透漏一下您输入niqe计算相似度的人脸图像尺寸以及 patch size大小吗？

**Comment by Lotayou** [comment]
Here
https://github.com/Lotayou/Face-Renovation/blob/7362555cf681981e0906d9bd89f3ded4fdfbd75f/metrics_package/niqe/niqe.py#L197-L201

**Comment by dan520520520** [comment]
谢谢，如果输入是68*68，您建议的patch size是？

**Comment by dan520520520** [comment]
谢谢，如果输入是68*68，您建议的patch size是？
这两天测试了把人脸裁剪到68*68，patch size = 15，好像效果还不错，
但是112*112好像没有找到合适的参数，关于NIQE使用到人脸图像上面，您有什么建议吗？








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lotayou/Face-Renovation"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月7日(星期五) 下午4:28
收件人:&nbsp;"Lotayou/Face-Renovation"<Face-Renovation@noreply.github.com&gt;;
抄送:&nbsp;"丹丹"<1049011336@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Lotayou/Face-Renovation] niqe (#14)





 
Closed #14.

**Comment by Lotayou** [comment]
不建议输入裁到68*68，在这么低的分辨率下人脸细节基本全损失了，用NIQE不太好评价细节的生成质量
