### ISSUE TITLE
生成图像存在色差问题

### ISSUE THREAD

**Issue by lxs802lxs8858** [Lotayou/Face-Renovation#15]
作者你好，我在用你的训练脚本训练你给的退化图像时（主要是用你退化脚本的去blurFFHQ），发现除了有彩色的artifact，还存在比较严重的色差问题，脚本其他地方没有任何改动，你们在训练的时候存在这个色差问题的现象吗？
![epoch-train-600-020](https://user-images.githubusercontent.com/33376135/91118973-bbfb2b80-e6c4-11ea-93c1-441a017e5c64.png)
中间是生成的结果，有比较明显的色差，并且这个现象比较普遍，很奇怪的是我并没有对代码做任何改动，直接拿来你的代码和退化方式去做的
这跟我把ngf改成了32有关系吗？（显存不够，跑batch=2必须要设置成32）

**Comment by Lotayou** [comment]
有可能，训练的前几个epoch是会有一点色差，但时间长一点（2天左右）基本颜色就一致了……可以试下batch_size=1,再把ngf 开大一点；再不行加个L1 loss约束一下，稍微舍弃一点perceptual quality
