### ISSUE TITLE
请问哪里可以下载到supplementary materials

### ISSUE THREAD

**Issue by hao-qiang** [Lotayou/Face-Renovation#2]
您好，拜读了您团队的论文，效果很惊艳，请问你们计划什么时候开源，还有是否可以提供supplementary materials下载链接，谢谢。

**Comment by Lotayou** [comment]
Hi, thanks for your appreciation of our work. Currently this work is under peer review and we will consider releasing the code and supplementary materials once the paper has been accepted. Stay tuned:)

**Comment by Lotayou** [comment]
Update: supplementary loaded
