### ISSUE TITLE
Upload pretrained models to google drive

### ISSUE THREAD

**Issue by AlexRMU** [Lotayou/Face-Renovation#20]
Please upload pretrained models to google drive. Download from ws28.cn very long, up to 2 hours, and sometimes the site doesn't work.

**Comment by Lotayou** [comment]
I cannot access google drive or dropbox from mainland China. Do you happen to know a viable website accessible from both Mainland China and overseas?

**Comment by AlexRMU** [comment]
VPN/proxy?

**Comment by AlexRMU** [comment]
https://www.reddit.com/r/China/comments/al9dvk/chinese_file_sharing_sites/
https://www.quora.com/Whats-the-best-file-sharing-service-to-share-with-the-people-in-China
idk

**Comment by olegkhomenko** [comment]
@Lotayou, 
You can use Yandex.Disk (Russian alternative to Google Drive). It is free to use.
https://disk.yandex.com

**Comment by Lotayou** [comment]
https://yadi.sk/d/Pl_hxVZPa_PHew
