### ISSUE TITLE
blue spots on my own training results

### ISSUE THREAD

**Issue by erjihaoshi** [Lotayou/Face-Renovation#21]
![00001-1](https://user-images.githubusercontent.com/37402962/97835820-f95be500-1d15-11eb-95b4-c4c6212ea992.jpg)
when I train  the HIFACEGAN，I use the FFHQ dataset and  degrade them  as train data
 I  set  netG = 'hifacegan'(not same as your 'lipspade')  ， ngf = 32 （11GB only for me） others are same as yours 。
but  I got asome results  as picture  illuminate(about 10%),  left is low quality ,middle is my results ,right is high orginal qualty image, I wanna konw why the model generate those blue spots.

**Comment by Lotayou** [comment]
The blue spot you observed is a typical artifact in semantic-guided synthesis called "droplet artifact", which is discussed in detail in [StyleGAN2](https://github.com/NVlabs/stylegan2) 

Please also refer to #12 for a similar issue.

**Comment by erjihaoshi** [comment]
Thanks for your reply.
