### ISSUE TITLE
Questions about the experimental part

### ISSUE THREAD

**Issue by raywzy** [Lotayou/Face-Renovation#3]
For the quantitative comparsions, how do you obtain the numerical scores such as PSNR, SSIM of other methods? Do you re-train all the methods using your own training data or just use their pretrained model?

**Comment by Lotayou** [comment]
We retrained (or fine-tuned) most of the methods on our dataset. However, some baselines did not release the training code (for instance [GFRNet](https://github.com/csxmli2016/GFRNet) and [RIDNet](https://github.com/saeed-anwar/RIDNet)), in which case we evaluate on the pretrained model instead.

**Comment by raywzy** [comment]
> We retrained (or fine-tuned) most of the methods on our dataset. However, some baselines did not release the training code (for instance [GFRNet](https://github.com/csxmli2016/GFRNet) and [RIDNet](https://github.com/saeed-anwar/RIDNet)), in which case we evaluate on the pretrained model instead.

Thanks for your reply. When do you plan to release the pretrained model? I reall want to try the performance.

**Comment by Lotayou** [comment]
> > We retrained (or fine-tuned) most of the methods on our dataset. However, some baselines did not release the training code (for instance [GFRNet](https://github.com/csxmli2016/GFRNet) and [RIDNet](https://github.com/saeed-anwar/RIDNet)), in which case we evaluate on the pretrained model instead.
> 
> Thanks for your reply. When do you plan to release the pretrained model? I reall want to try the performance.

This work is done at Alibaba and the code release is subject to company regulations. If you are keen to get started, try first switch the input of [SPADE](https://github.com/NVlabs/SPADE) with LQ face images and see if it works. Good luck:)

**Comment by Lotayou** [comment]
@raywzy Checkpoint released
