### ISSUE TITLE
To train own model using author's model

### ISSUE THREAD

**Issue by WeibinDai** [Lotayou/Face-Renovation#35]
First of all, thank you for your research and I learn much. Now, I want to use your model, 'latest_net_G.pth', as a pre-training model to train my own model with my own dataset, but I don't find anything like 'load_model(...)'. 
Is this interface provided in the source code? I'm looking forward to your reply. Thanks.

**Comment by Lotayou** [comment]
You can try specify `continue_train = True` in the config script, and delete the `iter.txt` file inside `checkpoints/XXX/`. This will clean the cache file for recording which epoch to resume training, and the program will automatically restart from epoch 1.
