### ISSUE TITLE
”Remind“——Using multi GPU training will get stuck.

### ISSUE THREAD

**Issue by LeeHW-THU** [Lotayou/Face-Renovation#37]
I get stuck when I train with multi GPU.
Using single card can run normally.

**Comment by Lotayou** [comment]
Thanks for noting, when I did this project I found a single GPU is adequate for most cases so I didn't pay close attention to multi-GPU support. This project is largely inherited from [SPADE](https://nvlabs.github.io/SPADE)，maybe you can look into it for a possible solution.
