### ISSUE TITLE
Pretained models?

### ISSUE THREAD

**Issue by Darrenxc** [Lotayou/Face-Renovation#8]

**Comment by Darrenxc** [comment]
Hi, your work is great, but I didn’t find the pre-trained models. do you have a plan to release them?

**Comment by NTU-P04922004** [comment]
I'm also looking forward to it, thanks.

**Comment by Lotayou** [comment]
This work is collaborated with Alibaba and I'm not at libetry to release models. You may have to train one yourself, should be straight-forward though. Good luck. Closing the issue now...

**Comment by Lotayou** [comment]
@Darrenxc @NTU-P04922004 Checkpoint released
